FROM python:bullseye

ENV DEBIAN_FRONTEND=noninteractive

RUN apt update && \ 
    apt install sudo python3-pyqt5 python3-pyqt5.qtwebengine openconnect -y && \
    rm -rf /var/lib/apt/lists/*

RUN pip install pyqt5 PyQtWebEngine

RUN pip install https://github.com/vlaci/openconnect-sso/releases/download/v0.8.0/openconnect_sso-0.8.0-py3-none-any.whl

COPY vpnc-script /usr/share/vpnc-scripts/vpnc-script

COPY runme.sh /usr/local/bin/runme.sh

COPY webengine_process.py /usr/local/lib/python3.11/site-packages/openconnect_sso/browser/webengine_process.py

RUN adduser --disabled-password --shell /bin/bash --gecos '' ubuntu

RUN adduser ubuntu sudo

RUN echo '%sudo ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers

USER ubuntu

WORKDIR /home/ubuntu

ENTRYPOINT [ "/usr/local/bin/runme.sh" ]
